name: Pytest

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.9"
            - name: Install APT dependencies
              run: |
                  sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
            - name: Install pip dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r core-requirements.txt
                  pip install -r qt-requirements.txt
                  pip install -r test-requirements.txt
                  pip install -r web-requirements.txt
            - name: Build GUI file
              run: |
                  pyside2-uic chameleon/qt/design.ui -o chameleon/qt/design.py
                  pyside2-uic chameleon/qt/filter_config.ui -o chameleon/qt/filter_config.py
            - name: Test with pytest
              uses: GabrielBB/xvfb-action@v1
              with:
                  run: |
                      pytest -v test/
              env:
                  QT_DEBUG_PLUGINS: 1
                  IS_GHA: 1
